# Generated by Django 2.2.3 on 2019-07-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duckchat', '0002_auto_20190716_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='icon',
            field=models.ImageField(default='user_icons/None/no-img.jpg', upload_to='user_icons/'),
        ),
    ]
